m1/Cargo.toml

Cargo.toml reflects intended rust 1.68.0

---

m1/.cargo/config.toml

Adds .cargo config into subnet.

updating .cargo

---

.github/workflows/release.yml
docker/release.dockerfile
scripts/install.sh

Improved logging for the installer, docker image build, and linux aarch64

---

.github/workflows/release.yml
docker/cli.dockerfile
docker/dev.dockerfile
docker/release.dockerfile

Dev and CLI Docker containers on Docker Hub are more useful and better branded than previously used ECR containers. These Docker Hub images were not being used and not included in automation, so as to limit last-minute changes to documentation. It is now deemed an appropriate time to update the automation.

[CICD] Add automation for Docker hub and changes available containers

---

.github/workflows/check.yml

[CICD] 1.69 latest

---

.github/workflows/check.yml
.github/workflows/coverage.yml
.github/workflows/release.yml
.github/workflows/test.yml

[BUILD] bumping to 1.70.

---

m1/Cargo.toml

[DEPS] pinning thiserror

---

m1/Cargo.toml
m1/movement/src/test/mod.rs

[DEPS] bumpin thiserror.

---

docker/dev.dockerfile

[CONTAINERS] dev

---

scripts/movementctl.sh

Adds a means to run m1 utilities in the foreground via movementctl.
This simplifies keeping processes in the foreground for common use cases such as running Docker containers as services.
`--foreground` flag now runs the respective command in the foreground.
Has been tested in local containers.

[CTL] add option to run in foreground.

---

scripts/movementctl.sh

[CTL] default to listening on all interfaces.

---

m1/.movement/config.yaml
m1/movement/src/common/init.rs

[CLI] Provides missing patch on init

---

.github/workflows/release.yml

This change attempts to introduce a CI/CD update which will add a tar.gz archive of the M1 repo with submodules included to the release. By doing so, we intend to support source downloads without requiring Git.

[CICD] m1-with-submodules release asset support.

---

.github/workflows/check.yml
.github/workflows/coverage.yml
.github/workflows/release.yml
.gitmodules
scripts/install.sh
scripts/movementctl.sh

[ECO:TESTING] changes to movementctl and installer to include management of ecosystem submodules.

---

.github/workflows/check.yml
.github/workflows/coverage.yml
.github/workflows/release.yml
.gitignore

[CI] fix internal repo access.

---

.github/workflows/release.yml

[CICD] bad token.

---

scripts/install.sh

[INSTALLER] variable subnet id w/ CI integration.

---

.github/workflows/commitlint.yml
commitlint.config.js

Adding commit lint

---

.devcontainer/ubuntu/Dockerfile
m1/scripts/start-subnet.sh

chore: lagging submodule.

---

m1/subnet/src/vm/mod.rs

Fixed wrong timestamp on chain

Fix issue #65:wrong timestamp on chain

---

.gitmodules

chore: m1-pre-core-v2 is now testnet.

---

.github/actions/setup-linux-aarch64/action.yml

fix: bad ga

---

CONTRIBUTING.md

Adds the `git submodule update --init --recursive` command to our docs.

update: update contributor docs

---

movement-sdk/clis/movement/Cargo.toml
scripts/install.sh

- Stop the installer from blocking installations via `--build` for non-Linux platforms. 
- Strips out vestigial logic for some dependency management which is now handled by `movement ctl manage`. 
- Renovates build dependency logic.
#115 and #105
- Stop the installer from blocking installations via `--build` for non-Linux platforms. 
- Strips out vestigial logic for some dependency management which is now handled by `movement ctl manage`. 
- Renovates build dependency logic.
I've tested manually and locally on MacOS Arm64 (M1) and in containers for Linux x86_64 and Linux Arm64.

fix: installer #115 #105.
